Repository yezz123/ormdantic, pull requests merged in 2022-08, with the labels that each got.

#10 ✨ Add Docstrings to classes
  .github/logo.png
  README.md
  pydanticORM/generator/_crud.py
  pydanticORM/generator/_table.py
  pydanticORM/orm.py
Labels: documentation

#12 chore(feat): Fix issue of similar to an existing project
  README.md
  pydanticORM/generator/__init__.py
  pydantic_orm/__init__.py
  pydantic_orm/generator/__init__.py
  pydantic_orm/generator/_crud.py
  pydantic_orm/generator/_table.py
  pydantic_orm/handler/__init__.py
  pydantic_orm/handler/errors.py
  pydantic_orm/handler/helper.py
  pydantic_orm/handler/snake.py
  pydantic_orm/orm.py
  pydantic_orm/py.typed
  pydantic_orm/table.py
  pydantic_orm/types/__init__.py
  pydantic_orm/types/base.py
  pyproject.toml
  scripts/lint.sh
  scripts/test.sh
  scripts/test_html.sh
  tests/test_errors.py
  tests/test_orm.py
  tests/test_otm_relations.py
  tests/test_version.py
Labels: enhancement

#15 Chore(feat): Improve many to many relationships & add New tests
  ormdantic/generator/_crud.py
  ormdantic/generator/_table.py
  ormdantic/orm.py
  ormdantic/table.py
  tests/test_m2m_relations.py
  tests/test_orm.py
Labels: bug, enhancement

#18 ✨ chore(fix): `Ormdantic` takes connection `str` instead of `engine`
  ormdantic/orm.py
  tests/test_errors.py
  tests/test_m2m_relations.py
  tests/test_orm.py
  tests/test_otm_relations.py
Labels: bug, enhancement

#23 Docs: Build Documentation for `Ormdantic`
  .github/workflows/docs.yml
  docs/code_of_conduct.md
  docs/contributing.md
  docs/faq.md
  docs/favicon.png
  docs/index.md
  docs/installation.md
  docs/license.md
  docs/usage.md
  mkdocs.yml
  pyproject.toml
Labels: documentation

#27 Convert comparison to SQLModel to table and update claims
  docs/faq.md
Labels: documentation, enhancement

#28 Fix code block format in comparison table
  docs/faq.md
Labels: documentation
