Repository yezz123/ormdantic, pull requests merged in 2022-10, with the labels that each got.

#42 :green_heart: Support Python 3.11
  .github/workflows/integration.yml
  .github/workflows/test.yml
Labels: dependencies

#44 fix: Improve field type translation
  ormdantic/generator/_table.py
  tests/test_orm.py
Labels: bug, enhancement

#50 ✨ Introduce the `count()` Feature
  .github/workflows/test.yml
  README.md
  docs/usage.md
  ormdantic/generator/_crud.py
  ormdantic/generator/_field.py
  tests/integration/demo.py
  tests/test_errors.py
  tests/test_orm.py
Labels: enhancement
